### ISSUE TITLE
failed to build shapeGeo  in UE5

### ISSUE THREAD

**Issue by chase03** [iwer/ShpGeometry#1]
>Log file: C:\Users\Administrator\AppData\Local\UnrealBuildTool\Log.txt
1>Creating makefile for CesiumForUnrealSamplesEditor (no existing makefile)
1>UnrealBuildTool : error : Unable to instantiate module 'GDAL': System.ComponentModel.Win32Exception (2): Le fichier spécifié est introuvable.
1>                           at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>                           at System.Diagnostics.Process.Start()
1>                           at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
1>                           at GDAL..ctor(ReadOnlyTargetRules Target) in F:\UE4_Projects\CesiumforUnrealSamples\Plugins\UnrealGDAL_Binaries-master\Source\GDAL\GDAL.Build.cs:line 196
1>                        (referenced via Target -> ShpGeometry.Build.cs)

Hi! Failed to build ShpGeometry in Unreal Engine, could you help me out and update those plugins ?  
Thanks!

**Comment by iwer** [comment]
Hi, it seems that there is a problem with the UnrealGDAL thirdparty libraries.

Did you manage to build gdal-ue4 and mergetiff-ue4 through conan-ue4cli (https://github.com/TensorWorks/UnrealGDAL#building-everything-from-source)?

There are some adaptions needed for ue4cli and conan-ue4cli to work with UE5, which can be found on several forks but I have not found the time to upgrade my stack to UE5.

**Comment by iwer** [comment]
Hi again, I made a [quick writeup](https://gist.github.com/iwer/fc4e34a2a491461d606d826b72664845) on how I got UnrealGDAL to compile with 5.1.
